version: '3'
services:
  database:
    container_name: MelodIO-mysql
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: MelodIO
    volumes:
      - ./database:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - melodio
  nginx:
    container_name: MelodIO-nginx
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - frontend
      - backend
    networks:
      - melodio
  backend:
    container_name: MelodIO-backend
    depends_on:
      database:
        condition: service_healthy
    ports:
      - "3000:3000"
    networks:
      - melodio
  frontend:
    container_name: MelodIO-frontend
    depends_on:
      - backend
    ports:
      - "5173:5173"
    networks:
      - melodio

networks:
  melodio:
    driver: bridge
