FROM node:18-alpine
WORKDIR /app/backend
RUN apk add --no-cache shadow
COPY package.json .
COPY package-lock.json .
COPY . .
RUN rm -rf node_modules
RUN npm i
EXPOSE 3000
CMD sleep 15 && npm run build && npm run start:prod